### ISSUE TITLE
Custom selectors for animations.

### ISSUE THREAD

**Issue by cv711** [KaneCohen/modal-vanilla#3]
Hi,

In my use case I am trying to use the `slideInDown` and `slideOutUp` from animations.css.
The slide in animation is easy because I can define it as the default in my dom.
The slide out on the other hand is trickier and can only be manipulated by toggling on and off the appropriate classes after the `dismiss` event and the `hidden` event to bring them back to the original state.

I saw the toggling of the `in` class, so I tried to use the code from `slideInDown` with it. The problem with this one is that the `in` class is being added a few millis later so you end up with a flickering effect of first seeing the modal in the centre and then the animation starts. 

It seems to me that this can be a common requirement so I would propose two configuration options with the css selector for custom in and out animations.

Thanks,
Chris

**Comment by KaneCohen** [comment]
@cv711 i'll see what could be done.

Modal object has a property called _templates which could be accessed on the instance. However, currently changing it won't affect rendering.

What do you think about following:

````
var myModal = Modal();
myModal._templates.container = '<div class="modal slideInDown"></div>';
````

This should add `slideInDown` class to the container. Is that something that might work for you?

**Comment by cv711** [comment]
No, I don't think this is solving my problem and the biggest problem is the "out" animation not the "in".

Essentially I want two things:
1) an `animationIn` option that I can give the `slideInDown` value and needs to be appended to the container's classList before **line 398** where the value of display attribute changes to `block`.
2) an `animationOut` option that I can override with a custom one like `slideOutUp` and needs to be added in container's classList inside the hide() function.

Can we do anything about those?

**Comment by KaneCohen** [comment]
@cv711, I think I understood you. When  you were talking about animations.css did you mean this one: <https://daneden.github.io/animate.css/>. I'd like to recreate first the usecase. If i'll consider adding this option I'd like to be sure that it would be something that would work in other situations beside one particular animations library.

In the meantime - have you considered using events in order to add/remove classes when needed?
For example (requires versions 0.2.11 - uploaded recently):

````js
var myModal = new Modal({el: someEl});
myModal.on('show', function() {
   myModal._html.container.classList.add('slideInDown'); 
});
myModal.on('shown', function() {
   myModal._html.container.classList.add('slideInDown'); 
});

myModal.on('hide', function() {
   myModal._html.container.classList.add('slideOutUp');
});
myModal.on('hidden', function() {
   myModal._html.container.classList.remove('slideOutUp');
});

**Comment by cv711** [comment]
Yeap, I used that lib as a reference point but I am not using the whole library, I have just extracted these two simple classes, which you can drop them in your tests:

```css
@keyframes slideInDown {
  from {
    transform: translate3d(0, -100%, 0);
    visibility: visible;
  }

  to {
    transform: translate3d(0, 0, 0);
  }
}

.slideInDown {
  animation-duration: .75s;
  animation-fill-mode: both;
  animation-name: slideInDown;
}


@keyframes slideOutUp {
  from {
    transform: translate3d(0, 0, 0);
  }

  to {
    visibility: hidden;
    transform: translate3d(0, -100%, 0);
  }
}

.slideOutUp {
  animation-duration: .75s;
  animation-fill-mode: both;
  animation-name: slideOutUp;
}
```

And yes I'm using the events to manipulate the animations in the meantime, thanks!
